### ISSUE TITLE
Update zope.interface to value greater than 5.0.0

### ISSUE THREAD

**Issue by andrewalexander** [ScanOC/trunk-player#77]
As per [this thread](https://github.com/pypa/setuptools/issues/2017#issuecomment-612691988) zope.interface appears to be importing an old version of setuptools that deprecated the `Feature` import. 

System:

linux kernel: 5.6.15-arch1-1GNU/Linux
python version: Python 3.8.3

I get this when running `pip install -r requirements.txt` in the virtualenv according to the docs:

```
Collecting zope.interface==4.4.3
  Using cached zope.interface-4.4.3.tar.gz (147 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/andrew/src/trunk-player/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rqdrat0_/zope.interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rqdrat0_/zope.interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-83nrrua7
         cwd: /tmp/pip-install-rqdrat0_/zope.interface/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rqdrat0_/zope.interface/setup.py", line 26, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/home/andrew/src/trunk-player/env/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

`pip install -r requirements.txt` works after updating the zope.Interface to 5.0.0:

```
Successfully built django-allauth django-select2 jsonfield msgpack-python oauthlib tinys3 twisted
Installing collected packages: six, asgiref, redis, msgpack-python, asgi-redis, attrs, txaio, autobahn, Automat, certifi, zope.interface, constantly, incremental, hyperlink, PyHamcrest, twisted, daphne, pytz, Django, channels, chardet, defusedxml, python3-openid, idna, urllib3, requests, oauthlib, requests-oauthlib, django-allauth, django-appconf, django-redis, django-select2, djangorestframework, jsonfield, stripe, pinax-stripe, psycopg2-binary, tinys3
Successfully installed Automat-0.6.0 Django-1.11.29 PyHamcrest-2.0.2 asgi-redis-1.4.3 asgiref-1.1.2 attrs-19.3.0 autobahn-17.10.1 certifi-2018.11.29 channels-1.1.8 chardet-3.0.4 constantly-15.1.0 daphne-1.3.0 defusedxml-0.5.0 django-allauth-0.34.0 django-appconf-1.0.2 django-redis-4.8.0 django-select2-6.0.1 djangorestframework-3.11.0 hyperlink-17.3.1 idna-2.8 incremental-17.5.0 jsonfield-1.0.3 msgpack-python-0.4.8 oauthlib-2.0.6 pinax-stripe-3.4.1 psycopg2-binary-2.8.5 python3-openid-3.1.0 pytz-2017.3 redis-2.10.6 requests-2.21.0 requests-oauthlib-0.8.0 six-1.11.0 stripe-1.75.0 tinys3-0.1.12 twisted-20.3.0 txaio-2.8.2 urllib3-1.24.3 zope.interface-5.0.0
```

 I can make the pull request if desired.

**Comment by dreinhold** [comment]
Cool, yes if submit a pull request i'll merge it in.

Dylan
